use serde::{Deserialize, Serialize};
use uuid::{Uuid, uuid};

#[derive(Debug, Clone, Copy, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum PersonType {
	Artist,
	Composer,
	Producer,
	/// A person with a secondary or "weak" association to a resource.
	///
	/// This variant is typically used for artists extracted from supplemental metadata, such as
	/// the `ARTISTS` tag generated by MusicBrainz (Picard) to list all contributors individually.
	///
	/// For example, for a track credited to "Mili feat. KIHOW", the `ARTISTS` tag would contain
	/// "Mili;KIHOW". These constituent artists are then linked as [PersonType::Weak].
	Weak,

	/// An unknown person type. Different from [Person::UNKNOWN_ID].
	///
	/// This variant is used when the person type cannot be determined from the tag.
	Unknown,
}

impl PersonType {
	pub fn from_tag(tag: &str) -> Self {
		match tag {
			"artist" => Self::Artist,
			"composer" => Self::Composer,
			"producer" => Self::Producer,
			_ => Self::Unknown,
		}
	}
}

#[derive(Debug, Serialize, Deserialize)]
pub struct Person {
	pub id: Uuid,
	pub name: String,
	pub name_sort: Option<String>,
	pub mbz_id: Option<String>,
}

impl Person {
	/// The UUID used to represent an unknown person to a resource. This is different from the [PersonType::Unknown].
	///
	/// Can be used for "Unknown Artist", "Unknown Composer", etc.
	pub const UNKNOWN_ID: Uuid = uuid!("00000000-0000-0000-0000-ffff00000001");

	pub fn temp(name: String, name_sort: Option<String>, mbz_id: Option<String>) -> Self {
		Self {
			id: Uuid::nil(),
			name,
			name_sort,
			mbz_id,
		}
	}

	pub fn as_new(&mut self) -> &Self {
		self.id = Uuid::now_v7();
		self
	}
}

#[derive(Debug, Serialize, Deserialize)]
pub struct InlinePerson {
	pub id: Uuid,
	pub resource_id: Uuid,
	#[serde(rename = "type")]
	pub type_: PersonType,
}

impl InlinePerson {
	/// Create an [InlinedArtist] that follows the default semantics for an unknown artist.
	pub fn unknown() -> Self {
		Self {
			id: Person::UNKNOWN_ID,
			resource_id: Uuid::nil(),
			type_: PersonType::Unknown,
		}
	}
}
