[target.x86_64-pc-windows-msvc]
rustflags = [
	"-C",
	"link-arg=dxva2.lib",
	"-C",
	"link-arg=evr.lib",
	"-C",
	"link-arg=mf.lib",
	"-C",
	"link-arg=mfplat.lib",
	"-C",
	"link-arg=mfplay.lib",
	"-C",
	"link-arg=mfreadwrite.lib",
	"-C",
	"link-arg=mfuuid.lib",
	"-C",
	"link-arg=bcrypt.lib",
	"-C",
	"link-arg=ws2_32.lib",
	"-C",
	"link-arg=Secur32.lib",
	"-C",
	"link-arg=Strmiids.lib",
	# "-C",
	# "link-arg=Mfplat.lib",
	# "-C",
	# "link-arg=Strmiids.lib",
	# "-C",
	# "link-arg=Mfuuid.lib",
	# "-C",
	# "link-arg=Bcrypt.lib",
	# "-C",
	# "link-arg=Secur32.lib",
	# "-C",
	# "link-arg=Ole32.lib",
	# "-C",
	# "link-arg=User32.lib",
]
