use gpui::{Hsla, SharedString};
use refineable::Refineable;
use serde::Deserialize;
use strum::EnumIter;

pub enum Appearance {
	Light,
	Dark,
}

#[derive(Debug, Clone, Copy, PartialEq, Default)]
pub enum WindowBackgroundContent {
	#[default]
	Opaque,
	Transparent,
	Blurred,
	#[cfg(target_os = "windows")]
	MicaBackdrop,
}

#[derive(Refineable, Debug, Clone, PartialEq)]
#[refineable(Debug, Deserialize)]
pub struct ThemeColors {
	pub background: Hsla,
	pub border: Hsla,
	pub border_disabled: Hsla,
	pub border_focused: Hsla,
	pub border_selected: Hsla,
	pub border_transparent: Hsla,
	pub border_variant: Hsla,
	pub conflict: Hsla,
	pub conflict_background: Hsla,
	pub conflict_border: Hsla,
	pub created: Hsla,
	pub created_background: Hsla,
	pub created_border: Hsla,
	pub deleted: Hsla,
	pub deleted_background: Hsla,
	pub deleted_border: Hsla,
	pub drop_target_background: Hsla,
	pub element_active: Hsla,
	pub element_background: Hsla,
	pub element_disabled: Hsla,
	pub element_hover: Hsla,
	pub element_selected: Hsla,
	pub elevated_surface_background: Hsla,
	pub error: Hsla,
	pub error_background: Hsla,
	pub error_border: Hsla,
	pub ghost_element_active: Hsla,
	pub ghost_element_background: Hsla,
	pub ghost_element_disabled: Hsla,
	pub ghost_element_hover: Hsla,
	pub ghost_element_selected: Hsla,
	pub hidden: Hsla,
	pub hidden_background: Hsla,
	pub hidden_border: Hsla,
	pub hint: Hsla,
	pub hint_background: Hsla,
	pub hint_border: Hsla,
	pub icon: Hsla,
	pub icon_accent: Hsla,
	pub icon_disabled: Hsla,
	pub icon_muted: Hsla,
	pub icon_placeholder: Hsla,
	pub ignored: Hsla,
	pub ignored_background: Hsla,
	pub ignored_border: Hsla,
	pub info: Hsla,
	pub info_background: Hsla,
	pub info_border: Hsla,
	pub link_text_hover: Hsla,
	pub modified: Hsla,
	pub modified_background: Hsla,
	pub modified_border: Hsla,
	pub pane_focused_border: Hsla,
	pub pane_group_border: Hsla,
	pub panel_background: Hsla,
	pub panel_focused_border: Hsla,
	pub panel_indent_guide: Hsla,
	pub panel_indent_guide_active: Hsla,
	pub panel_indent_guide_hover: Hsla,
	pub renamed: Hsla,
	pub renamed_background: Hsla,
	pub renamed_border: Hsla,
	pub scrollbar_thumb_background: Hsla,
	pub scrollbar_thumb_border: Hsla,
	pub scrollbar_thumb_hover_background: Hsla,
	pub scrollbar_track_background: Hsla,
	pub scrollbar_track_border: Hsla,
	pub search_match_background: Hsla,
	pub status_bar_background: Hsla,
	pub success: Hsla,
	pub success_background: Hsla,
	pub success_border: Hsla,
	pub surface_background: Hsla,
	pub tab_active_background: Hsla,
	pub tab_inactive_background: Hsla,
	pub tab_bar_background: Hsla,
	pub text: Hsla,
	pub text_accent: Hsla,
	pub text_disabled: Hsla,
	pub text_muted: Hsla,
	pub text_placeholder: Hsla,
	pub title_bar_background: Hsla,
	pub title_bar_inactive_background: Hsla,
	pub toolbar_background: Hsla,
	pub warning: Hsla,
	pub warning_background: Hsla,
	pub warning_border: Hsla,
}

#[derive(Refineable, Debug, Clone, PartialEq)]
pub struct ThemeStyles {
	pub window_background: WindowBackgroundContent,
	#[refineable]
	pub colors: ThemeColors,
}

#[derive(Debug, Clone)]
pub struct Theme {
	pub id: String,
	pub name: SharedString,
	pub styles: ThemeStyles,
}

#[derive(EnumIter, Debug, Clone, Copy)]
pub enum ThemeColorField {
	Background,
	Border,
	BorderDisabled,
	BorderFocused,
	BorderSelected,
	BorderTransparent,
	BorderVariant,
	Conflict,
	ConflictBackground,
	ConflictBorder,
	Created,
	CreatedBackground,
	CreatedBorder,
	Deleted,
	DeletedBackground,
	DeletedBorder,
	DropTargetBackground,
	ElementActive,
	ElementBackground,
	ElementDisabled,
	ElementHover,
	ElementSelected,
	ElevatedSurfaceBackground,
	Error,
	ErrorBackground,
	ErrorBorder,
	GhostElementActive,
	GhostElementBackground,
	GhostElementDisabled,
	GhostElementHover,
	GhostElementSelected,
	Hidden,
	HiddenBackground,
	HiddenBorder,
	Hint,
	HintBackground,
	HintBorder,
	Icon,
	IconAccent,
	IconDisabled,
	IconMuted,
	IconPlaceholder,
	Ignored,
	IgnoredBackground,
	IgnoredBorder,
	Info,
	InfoBackground,
	InfoBorder,
	LinkTextHover,
	Modified,
	ModifiedBackground,
	ModifiedBorder,
	PaneFocusedBorder,
	PaneGroupBorder,
	PanelBackground,
	PanelFocusedBorder,
	PanelIndentGuide,
	PanelIndentGuideActive,
	PanelIndentGuideHover,
	Renamed,
	RenamedBackground,
	RenamedBorder,
	ScrollbarThumbBackground,
	ScrollbarThumbBorder,
	ScrollbarThumbHoverBackground,
	ScrollbarTrackBackground,
	ScrollbarTrackBorder,
	SearchMatchBackground,
	StatusBarBackground,
	Success,
	SuccessBackground,
	SuccessBorder,
	SurfaceBackground,
	TabActiveBackground,
	TabInactiveBackground,
	TabBarBackground,
	Text,
	TextAccent,
	TextDisabled,
	TextMuted,
	TextPlaceholder,
	TitleBarBackground,
	TitleBarInactiveBackground,
	ToolbarBackground,
	Warning,
	WarningBackground,
	WarningBorder,
}

impl ThemeColors {
	pub fn get(&self, field: ThemeColorField) -> Hsla {
		match field {
			ThemeColorField::Background => self.background,
			ThemeColorField::Border => self.border,
			ThemeColorField::BorderDisabled => self.border_disabled,
			ThemeColorField::BorderFocused => self.border_focused,
			ThemeColorField::BorderSelected => self.border_selected,
			ThemeColorField::BorderTransparent => self.border_transparent,
			ThemeColorField::BorderVariant => self.border_variant,
			ThemeColorField::Conflict => self.conflict,
			ThemeColorField::ConflictBackground => self.conflict_background,
			ThemeColorField::ConflictBorder => self.conflict_border,
			ThemeColorField::Created => self.created,
			ThemeColorField::CreatedBackground => self.created_background,
			ThemeColorField::CreatedBorder => self.created_border,
			ThemeColorField::Deleted => self.deleted,
			ThemeColorField::DeletedBackground => self.deleted_background,
			ThemeColorField::DeletedBorder => self.deleted_border,
			ThemeColorField::DropTargetBackground => self.drop_target_background,
			ThemeColorField::ElementActive => self.element_active,
			ThemeColorField::ElementBackground => self.element_background,
			ThemeColorField::ElementDisabled => self.element_disabled,
			ThemeColorField::ElementHover => self.element_hover,
			ThemeColorField::ElementSelected => self.element_selected,
			ThemeColorField::ElevatedSurfaceBackground => self.elevated_surface_background,
			ThemeColorField::Error => self.error,
			ThemeColorField::ErrorBackground => self.error_background,
			ThemeColorField::ErrorBorder => self.error_border,
			ThemeColorField::GhostElementActive => self.ghost_element_active,
			ThemeColorField::GhostElementBackground => self.ghost_element_background,
			ThemeColorField::GhostElementDisabled => self.ghost_element_disabled,
			ThemeColorField::GhostElementHover => self.ghost_element_hover,
			ThemeColorField::GhostElementSelected => self.ghost_element_selected,
			ThemeColorField::Hidden => self.hidden,
			ThemeColorField::HiddenBackground => self.hidden_background,
			ThemeColorField::HiddenBorder => self.hidden_border,
			ThemeColorField::Hint => self.hint,
			ThemeColorField::HintBackground => self.hint_background,
			ThemeColorField::HintBorder => self.hint_border,
			ThemeColorField::Icon => self.icon,
			ThemeColorField::IconAccent => self.icon_accent,
			ThemeColorField::IconDisabled => self.icon_disabled,
			ThemeColorField::IconMuted => self.icon_muted,
			ThemeColorField::IconPlaceholder => self.icon_placeholder,
			ThemeColorField::Ignored => self.ignored,
			ThemeColorField::IgnoredBackground => self.ignored_background,
			ThemeColorField::IgnoredBorder => self.ignored_border,
			ThemeColorField::Info => self.info,
			ThemeColorField::InfoBackground => self.info_background,
			ThemeColorField::InfoBorder => self.info_border,
			ThemeColorField::LinkTextHover => self.link_text_hover,
			ThemeColorField::Modified => self.modified,
			ThemeColorField::ModifiedBackground => self.modified_background,
			ThemeColorField::ModifiedBorder => self.modified_border,
			ThemeColorField::PaneFocusedBorder => self.pane_focused_border,
			ThemeColorField::PaneGroupBorder => self.pane_group_border,
			ThemeColorField::PanelBackground => self.panel_background,
			ThemeColorField::PanelFocusedBorder => self.panel_focused_border,
			ThemeColorField::PanelIndentGuide => self.panel_indent_guide,
			ThemeColorField::PanelIndentGuideActive => self.panel_indent_guide_active,
			ThemeColorField::PanelIndentGuideHover => self.panel_indent_guide_hover,
			ThemeColorField::Renamed => self.renamed,
			ThemeColorField::RenamedBackground => self.renamed_background,
			ThemeColorField::RenamedBorder => self.renamed_border,
			ThemeColorField::ScrollbarThumbBackground => self.scrollbar_thumb_background,
			ThemeColorField::ScrollbarThumbBorder => self.scrollbar_thumb_border,
			ThemeColorField::ScrollbarThumbHoverBackground => self.scrollbar_thumb_hover_background,
			ThemeColorField::ScrollbarTrackBackground => self.scrollbar_track_background,
			ThemeColorField::ScrollbarTrackBorder => self.scrollbar_track_border,
			ThemeColorField::SearchMatchBackground => self.search_match_background,
			ThemeColorField::StatusBarBackground => self.status_bar_background,
			ThemeColorField::Success => self.success,
			ThemeColorField::SuccessBackground => self.success_background,
			ThemeColorField::SuccessBorder => self.success_border,
			ThemeColorField::SurfaceBackground => self.surface_background,
			ThemeColorField::TabActiveBackground => self.tab_active_background,
			ThemeColorField::TabInactiveBackground => self.tab_inactive_background,
			ThemeColorField::TabBarBackground => self.tab_bar_background,
			ThemeColorField::Text => self.text,
			ThemeColorField::TextAccent => self.text_accent,
			ThemeColorField::TextDisabled => self.text_disabled,
			ThemeColorField::TextMuted => self.text_muted,
			ThemeColorField::TextPlaceholder => self.text_placeholder,
			ThemeColorField::TitleBarBackground => self.title_bar_background,
			ThemeColorField::TitleBarInactiveBackground => self.title_bar_inactive_background,
			ThemeColorField::ToolbarBackground => self.toolbar_background,
			ThemeColorField::Warning => self.warning,
			ThemeColorField::WarningBackground => self.warning_background,
			ThemeColorField::WarningBorder => self.warning_border,
		}
	}
}
